# Generated by Django 4.0.5 on 2022-06-28 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('authorFirstName', models.CharField(max_length=500)),
                ('authorLastName', models.CharField(max_length=500)),
                ('authorBiography', models.TextField()),
                ('publisher', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('ISBN', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('bookTitle', models.CharField(max_length=500)),
                ('bookDescription', models.TextField()),
                ('bookPrice', models.CharField(max_length=7)),
                ('bookAuthor', models.CharField(max_length=500)),
                ('bookGenre', models.CharField(max_length=500)),
                ('publisher', models.CharField(max_length=500)),
                ('publishYear', models.CharField(max_length=4)),
                ('bookCopiesSold', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=1)),
                ('ratingDate', models.DateField(auto_now_add=True)),
                ('userName', models.CharField(max_length=50)),
                ('ISBN_RATING', models.ManyToManyField(to='books.books')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookComment', models.CharField(max_length=10000)),
                ('commentDate', models.DateField(auto_now_add=True)),
                ('userName', models.CharField(max_length=50)),
                ('ISBN_COMMENT', models.ManyToManyField(to='books.books')),
            ],
        ),
    ]
