# Generated by Django 4.0.5 on 2022-06-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('authorFirstName', models.CharField(max_length=500)),
                ('authorLastName', models.CharField(max_length=500)),
                ('authorBiography', models.TextField()),
                ('publisher', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('ISBN', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('bookTitle', models.CharField(max_length=500)),
                ('bookDescription', models.TextField()),
                ('bookPrice', models.CharField(max_length=7)),
                ('bookAuthor', models.CharField(max_length=500)),
                ('bookGenre', models.CharField(max_length=500)),
                ('publisher', models.CharField(max_length=500)),
                ('publishYear', models.CharField(max_length=4)),
                ('bookCopiesSold', models.CharField(max_length=500)),
            ],
        ),
    ]
