# Generated by Django 4.0.5 on 2022-06-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('ISBN', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('bookComment', models.CharField(max_length=500)),
                ('commentDate', models.DateField()),
                ('userName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('ISBN', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('rating', models.CharField(max_length=1)),
                ('ratingDate', models.DateField()),
                ('userName', models.CharField(max_length=50)),
            ],
        ),
    ]
