# Generated by Django 4.0.5 on 2022-07-04 21:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('homeAddress', models.CharField(max_length=500)),
                ('creditCard', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9999999999999999)])),
            ],
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='ISBN_C',
            new_name='ISBN_COMMENT',
        ),
        migrations.RenameField(
            model_name='ratings',
            old_name='ISBN_R',
            new_name='ISBN_RATING',
        ),
    ]
