# Generated by Django 4.0.5 on 2022-06-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_comments_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='bookComment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comments',
            name='commentDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='ratingDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
