# Generated by Django 4.0.5 on 2022-07-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_profile_rename_isbn_c_comments_isbn_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='creditCard',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AddField(
            model_name='profile',
            name='profileID',
            field=models.AutoField(default='', primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankName', models.CharField(max_length=100)),
                ('creditCard', models.CharField(max_length=16, unique=True)),
                ('username_creditCard', models.ManyToManyField(to='books.profile')),
            ],
        ),
    ]
