# Generated by Django 4.0.5 on 2022-06-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_comments_bookcomment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='bookComment',
            field=models.CharField(max_length=10000),
        ),
    ]
