# Generated by Django 4.0.5 on 2022-06-27 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_comments_bookcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='commentDate',
        ),
    ]
