# Generated by Django 4.0.5 on 2022-06-27 20:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_comments_commentdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='commentDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
